### ISSUE TITLE
Existing approaches and design for hyperparameter-tuning

### ISSUE THREAD

**Issue by ddutta** [kubeflow/hp-tuning#2]
https://github.com/tobegit3hub/advisor 
https://github.com/CiscoAI/hyper-advisor-client 
https://github.com/mlkube/katib 

Please feel free to add ...

**Comment by gaocegege** [comment]
We are trying to collaborate with @libbyandhelen to implement more algorithms which is in advisor or ciscoAI's client, thus going to close the issue. Feel free to leave comments if you have any thought about it.
