### ISSUE TITLE
[discussion] Find a new way to install CLI

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/hp-tuning#26]
ref https://github.com/kubeflow/hp-tuning/pull/25#issue-180227251

I think we could find a better way to install the cli.

**Comment by YujiOshima** [comment]
I can come up with at the moment as below.
* With go schema
	* The easiest way, You can simply do `go get github.com/kubeflow/hp-tuning/cli`.
	But it's difficult to specify the version.
	* Build from source. Thanks to your PR, we can build cli without `go get` every package.

* Using GitHub release. Push binary with manually or CI, and download it.

**Comment by gaocegege** [comment]
We released a version, then we could push the binaries to it.
