### ISSUE TITLE
Provide a cli binary for macOS / darwin

### ISSUE THREAD

**Issue by ankushagarwal** [kubeflow/hp-tuning#57]
The current alpha release only provides a cli binary for linux-amd64. Would be nice to have a build for macOS / darwin as well

/cc @gaocegege

**Comment by ankushagarwal** [comment]
You don't need access to macOS to build macOS binaries

You can simply run this in your linux environment

`env GOOS=darwin GOARCH=amd64 go build github.com/kubeflow/hp-tuning/cli`

Reference : https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04

**Comment by gaocegege** [comment]
OK, thanks.

**Comment by gaocegege** [comment]
Added, thanks

**Comment by ankushagarwal** [comment]
Thank you!
